### ISSUE TITLE
error when i try to start bancho.py

### ISSUE THREAD

**Issue by Tian-MC** [osuAkatsuki/bancho.py#313] opened 2022-12-15 02:37 UTC
Hi, today i wanted create a osu private server.
but when i try to start it, it gives me this:

`bancho.py v4.6.4 ran into an issue before starting up :(
Traceback (most recent call last):
  File "/home/ubuntu/bancho.py/./main.py", line 135, in <module>
    raise SystemExit(main(sys.argv[1:]))
  File "/home/ubuntu/bancho.py/./main.py", line 112, in main
    raise ValueError(
ValueError: '/tmp/bancho.sock' does not appear to be an IPv4, IPv6 or Unix address`

anyone can help me?

**Comment by cmyui** [comment] 2022-12-28 16:32
Hey, sorry I'm really not sure how I missed this, I haven't been checking Issues lately 🤔 

Did you figure this out?

**Comment by cmyui** [comment] 2023-01-08 08:29
Going to close this - feel free to re-open if the problem is still hindering you from starting the server!

**Closed by cmyui** 2023-01-08 08:29 UTC
